name: "Build and deploy folketrygdbeholdning"
on:
  push:
    branches:
    - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":

    name: "build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
    - uses: "gradle/wrapper-validation-action@v1"

    - uses: actions/cache@v2
      with:
        "path": "~/.gradle/caches"
        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
        "restore-keys": "${{ runner.os }}-gradle-"

    - uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: temurin

    - name: "compile and run tests"
      run: ./gradlew build
      env:
        GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}

    - name: "Login to GitHub Docker Registry"
      uses: docker/login-action@v2
      with:
        "registry": "ghcr.io"
        "username": "${{ github.actor }}"
        "password": "${{ secrets.GITHUB_TOKEN }}"

    - name: "Build and push the Docker image"
      run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"

  "deployAppToDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Deploy to DEV-GCP"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-gcp"
        "RESOURCE": ".nais/dev.yaml"
