name: "Build and deploy folketrygdbeholdning"
on:
  push:
    branches:
    - "main"
env:
  "IMAGE_BASE": "ghcr.io/${{ github.repository }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
      packages: write
    outputs:
      image: ${{ steps.version.outputs.image }}
    steps:
    - uses: actions/checkout@v3
    - uses: "gradle/wrapper-validation-action@v1"

    - uses: actions/cache@v3.3.1
      with:
        "path": "~/.gradle/caches"
        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
        "restore-keys": "${{ runner.os }}-gradle-"

    - uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: temurin

    - name: "compile and run tests"
      run: ./gradlew build
      env:
        GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}

    - name: set version
      id: version
      run: |
        export TZ=CET
        TAG=$(date "+%Y.%m.%d_%H-%M")-$(git rev-parse --short HEAD)
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "::set-output name=tag::$TAG"
        echo "IMAGE=$IMAGE_BASE:$TAG" >> $GITHUB_ENV
        echo "::set-output name=image::$IMAGE_BASE:$TAG"

    - name: "Login to GitHub Docker Registry"
      uses: docker/login-action@v2.2.0
      with:
        "registry": "ghcr.io"
        "username": "${{ github.actor }}"
        "password": "${{ secrets.GITHUB_TOKEN }}"

    - name: "Build and push the Docker image"
      run: "docker build --pull --tag ${env.IMAGE} . && docker push ${env.IMAGE}"

  "deployAppToDev":
    name: "Deploy app to dev"
    permissions:
      contents: "read"
      id-token: "write"
      packages: write
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - name: "Deploy to DEV-GCP"
      uses: "nais/deploy/actions/deploy@v2"
      env:
        "CLUSTER": "dev-gcp"
        "RESOURCE": ".nais/dev.yaml"
        "IMAGE": "${{ needs.build.outputs.image }}"

